-- CARREGA OBSTACULO
INSERT INTO OBSTACLE VALUES ('CARRO POLICIA','POLICECAR',0,-1.87,-3.4,2);
INSERT INTO OBSTACLE VALUES ('CARRO CIVIL','CIVILCAR',0,-1.46,-3.25,2);
INSERT INTO OBSTACLE VALUES ('HIDRANTE','HIDRANTE',-0.81,0,0,3);

-- CARREGA PLAYER
INSERT INTO PLAYER VALUES ('tbelem','123456',SYSDATETIME(),'tiago.mb95@gmail.com','Nome da mãe ?','Anabele Silveira');
INSERT INTO PLAYER_CURRENCY VALUES (1,0,0,0,0,0,0,0,0);