-- CARREGA OBSTACULO
INSERT INTO OBSTACLE VALUES ('CARRO POLICIA','POLICECAR',0,-1.87,-3.4,2);
INSERT INTO OBSTACLE VALUES ('CARRO CIVIL','CIVILCAR',0,-1.46,-3.25,2);
INSERT INTO OBSTACLE VALUES ('HIDRANTE','HIDRANTE',-0.81,0,0,3);

-- CARREGA PLAYER
INSERT INTO PLAYER VALUES ('tbelem','123456',SYSDATETIME(),'tiago.mb95@gmail.com','Nome da mãe ?','Anabele Silveira');
INSERT INTO PLAYER_CURRENCY VALUES (1,0,0,0,0,0,0,0,0);
INSERT INTO PLAYER_ITEM VALUES (1,1,1);
INSERT INTO PLAYER_ITEM VALUES (1,6,1);

-- CARREGA ITENS
INSERT INTO ITEM values ('PADRAO','none',0,1);
INSERT INTO ITEM values ('COROA AZUL','blue_crown',300,1);
INSERT INTO ITEM values ('CHAPEU PRETO','black_hat',1000,1);
INSERT INTO ITEM values ('CHAPEU MARROM','brown_hat',1500,1);
INSERT INTO ITEM values ('COROA DOURADA','gold_crown',3000,1);

INSERT INTO ITEM values ('CARRO VERMELHO',NULL,0,2);
INSERT INTO ITEM values ('CARRO AZUL',NULL,350,2);
INSERT INTO ITEM values ('CARRO VERDE',NULL,1250,2);
INSERT INTO ITEM values ('CARRO AMARELO',NULL,3000,2);
INSERT INTO ITEM values ('CARRO LILAS',NULL,5000,2);